config/routes.rb
Themeindo::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, 
    controllers: { 
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
      sessions: 'sessions',
      confirmations: "confirmations"
    }, 
    path_names: { 
      sign_in:  'login', 
      sign_out: 'logout', 
      sign_up:  'register' 
    }
    
  concern :startup_backend, Startup::BackendRoutes.new
  namespace :backend do
    concerns :startup_backend
  end

  concern :startup_member, Startup::MemberRoutes.new
  namespace :member do
    concerns :startup_member
  end

  root 'publics#home'
  get '/backend',                   to: 'backend#home',                     as: 'backend_home'
  get '/member',                    to: 'member#home',                      as: 'member_home'
  get '/profile',                   to: 'member#profile',                   as: 'profile'
  get 'search',                     to: 'publics#search',                   as: 'search'
  get 'portfolio/:id',              to: 'publics#portfolio',                as: 'portfolio'
  get "like/:id",                   to: "publics#upvote",                   as: 'like'
  get "document_download/:id",      to: "publics#document_download",        as: 'document_download'
  get "landing_page/:id",           to: "publics#landing_page",             as: 'landing_page'
  
  get "catalog_category_child",     to: "catalogs#catalog_category_child",  as: 'catalog_category_child'

  # Success review order
  get "review/:id",                 to: "orders#review",                    as: 'review'

  resources :catalogs do
    member do
      get 'comments'
      get 'support'
      get 'ticket'
      put "like",     to: "catalogs#upvote"
      match :upvote, path: 'like', via: [:get, :post, :put]
    end
  end

  resource :orders do
    collection do
      get :paid
      get :revoked
      post :ipn
    end
  end

  resources :order_items, only: [:create, :update, :destroy]
  resources :comments
  resources :tickets
  resources :subscribes

  # namespace :api do
  #   namespace :v1 do 
  #     resources :catalogs, only: [:index, :show] do 
  #       member do
  #         get 'comments'
  #         get 'support'
  #         get 'ticket'
  #         put "like",     to: "catalogs#upvote"
  #         match :upvote, path: 'like', via: [:get, :post, :put]
  #       end
  #     end
  #   end
  # end


end

app/views/backend/shareds/home/_bar_chart.html.erb
<div class="row-fluid">
  <div class="widget span6">
    <div class="widget-header"><i class="icon-signal"></i><h5>Bar Chart</h5>
    <div class="widget-buttons">
        <a href="javascript:void(0)" class="collapse" data-collapsed="false"><i data-title="Collapse" class="icon-chevron-up"></i></a>
    </div>
    </div>
    <div class="widget-body clearfix">
      <div class="analytics_item" id="barchart"></div>
    </div>
  </div>
  <div class="widget span3">
    <div class="widget-header">
      <i class="icon-signal"></i><h5>Browsers</h5>
      <div class="widget-buttons">
        <a href="javascript:void(0)" class="collapse" data-collapsed="false">
          <i data-title="Collapse" class="icon-chevron-up"></i>
        </a>
      </div>
    </div>
    <div class="widget-header-under">The preferred browsers of your users</div>
    <div class="widget-body clearfix" style="min-height: 319px;">
      <table class="table table-striped">
        <thead>
            <tr>
              <th>Browser</th>
              <th>Visits</th>
            </tr>
        </thead>
        <tbody>
          <tr>
            <td>Firefox</td>
            <td><strong>5798</strong></td>
          </tr>
          <tr>
            <td>Chrome</td>
            <td><strong>4855</strong></td>
          </tr>
          <tr>
            <td>Internet Explorer</td>
            <td><strong>2877</strong></td>
          </tr>
          <tr>
            <td>Safari</td>
            <td><strong>2705</strong></td>
          </tr>
          <tr>
            <td>Opera</td>
            <td><strong>1985</strong></td>
          </tr>
          <tr>
            <td>Android Browser</td>
            <td><strong>1581</strong></td>
          </tr>
          <tr>
            <td>RockMelt</td>
            <td><strong>1284</strong></td>
          </tr>
        </tbody>      
      </table>
    </div>
  </div>
  <div class="widget span3">
    <div class="widget-header"><i class="icon-signal"></i><h5>Most active pages</h5>
      <div class="widget-buttons">
        <a href="javascript:void(0)" class="collapse" data-collapsed="false"><i data-title="Collapse" class="icon-chevron-up"></i></a>
      </div>
    </div>
    <div class="widget-header-under">The most visited pages by your users</div>
    <div class="widget-body clearfix" style="min-height: 319px;">
      <table class="table table-striped">
        <thead>
            <tr>
              <th>Page</th>
              <th>Visits</th>
            </tr>
        </thead>
        <tbody>
          <tr>
            <td>Categories</td>
            <td><strong>8790</strong></td>
          </tr>
          <tr>
            <td>Clothing</td>
            <td><strong>7052</strong></td>
          </tr>
          <tr>
            <td>About</td>
            <td><strong>6577</strong></td>
          </tr>
          <tr>
            <td>Contact Us</td>
            <td><strong>5760</strong></td>
          </tr>
          <tr>
            <td>Blog</td>
            <td><strong>4876</strong></td>
          </tr>
          <tr>
            <td>Prices</td>
            <td><strong>3866</strong></td>
          </tr>
          <tr>
            <td>Information</td>
            <td><strong>1876</strong></td>
          </tr>
        </tbody>      
      </table>
    </div>
  </div>
</div>

app/views/backend/shareds/home/_bar_quick.html.erb
<div class="row-fluid">
  <div class="widget span12" style="overflow:visible;">
    <a class="btn btn-box bubble bubble-danger span2 tips" data-title="bubble-danger" href="#" data-bubble="5k">
    	<i class="icon-user"></i><span>Users</span>
    </a>
    <a class="btn btn-box span2" href="#">
    	<i class="icon-plus-sign"></i><span>Notifications</span>
    </a>
    <a class="btn btn-box span2" href="#">
    	<i class="icon-calendar"></i><span>Calendar</span>
    </a>
    <a class="btn btn-box bubble bubble-info span2 tips" data-title="bubble-info" href="#" data-bubble="2">
    	<i class="icon-signal"></i><span>Analytics</span>
    </a>
    <a class="btn btn-box span2" href="#" data-bubble="2">
    	<i class="icon-lightbulb"></i><span>Tickets</span>
    </a>
    <a class="btn btn-box bubble bubble-success span2 tips" data-title="bubble-success" href="#" data-bubble="102">
    	<i class="icon-sitemap"></i><span>Categories</span>
    </a>
  </div>
</div>

app/views/backend/shareds/home/_overview_activity.html.erb
<div class="row-fluid">
  <div class="widget span4">
    <div class="widget-header">
      <i class="icon-lightbulb"></i>
      <h5>Recent Support Tickets</h5>
      <div class="widget-buttons">
          <a href="javascript:void(0)" class="collapse" data-collapsed="false"><i data-title="Collapse" class="icon-chevron-up"></i></a>
      </div>
    </div>  
    <div class="widget-body" style="height:310px;overflow:hidden">
      <div class="widget-tickets clearfix slimscroll">
        <ul>
          <% @root_tickets.limit(20).each do |ticket| %>
            <li class="priority-high">
              <%= link_to backend_ticket_path(ticket) do %>
                <%= image_tag ticket.try(:user).try(:profile).try(:avatar).url(:small), class: 'avatar' %>
                <h5><%= ticket.try(:user).try(:profile).try(:full_name) %></h5>
                <p><%= ticket.title %></p>
                <div class="date"><%= ticket.try(:created_at).strftime("%H:%M %B, %d, %Y") %></div>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div><!--/widget-body-->
    <div class="widget-footer">
      <%= link_to backend_tickets_path, class: "pull-right btn btn-small" do %>
        <i class="icon-plus"></i> Load More
      <% end %>
    </div>
  </div> <!-- /widget span5 -->

  <div class="widget span8">
    <div class="widget-header">
      <i class="icon-comment-alt"></i>
      <h5>Recent Comments</h5>
      <div class="widget-buttons">
        <a href="javascript:void(0)" class="collapse" data-collapsed="false">
          <i data-title="Collapse" class="icon-chevron-up"></i>
        </a>
      </div>
    </div>  
    <div class="widget-body" style="height:310px;overflow:hidden">
      <div class="widget-comments clearfix slimscroll">
        <ul>
          <% @root_comments.limit(10).each do |comment| %>
            <li>
              <%= image_tag comment.try(:user).try(:profile).try(:avatar).url(:small), class: "avatar" %>
              <div class="comment-bubble">
                <h4>
                  <%= comment.try(:user).try(:profile).try(:full_name) %> - <strong><%= comment.try(:user).try(:username) %></strong>
                </h4>
                <%= truncate comment.try(:comment), length: 45 %>
                <div class="date"><%= comment.try(:created_at).strftime("%H:%M %B, %d, %Y") %></div>
                <div class="settings">
                  <%= link_to comments_catalog_path(comment.commentable.slug, reply: true, to: comment.id), class: "tip" do %>
                    <i class="icon-reply"></i> More
                  <% end %>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div><!--/widget-body-->
    <div class="widget-footer">
      <%= link_to backend_comments_path, class: "pull-right btn btn-small" do %>
        <i class="icon-plus"></i> Load More
      <% end %>
    </div>
  </div> <!-- /widget span5 -->
</div> <!-- /row-fluid -->

app/views/backend/shareds/home/_overview_boxes.html.erb
<div class="row-fluid">
  <div class="overview_boxes">
    <div class="box_row clearfix">
      <div class="widget-tasks-statistics">
        <div class="userstats clearfix" style="margin-top: 25px;">
            <a href="javascript:void(0)" data-toggle="modal" data-target="#example_modal2">
            <div class="white">
              <i style="color:#E28271" class="icon-eye-open"></i>
              <p style="color:#E28271">+85%</p>
            </div>
            <div class="widget">
              <input class="knob" data-width="120" data-height="120" data-displayInput=false data-readOnly=true data-thickness=".15" value="85">   
            </div>
            <p><strong>+530</strong>Visits this month</p>
          </a>
        </div>
      </div>
      <div class="widget-tasks-statistics">
        <div class="userstats clearfix" style="margin-top: 25px;">
            <a href="javascript:void(0)" data-toggle="modal" data-target="#example_modal2">
            <div class="white">
              <i style="color:#98E5EA" class="icon-user"></i>
              <p style="color:#98E5EA"><%= @latest_members.size %></p>
            </div>
            <div class="widget">
              <input class="knob" data-width="120" data-height="120" data-displayInput=false data-readOnly=true data-thickness=".15" value="<%= @latest_members.size %>">   
            </div>
            <p><strong><%= @latest_members.size %></strong>Members</p>

          </a>
        </div>
      </div>
      <div class="widget-tasks-statistics">
        <div class="userstats clearfix" style="margin-top: 25px;">
            <a href="javascript:void(0)" data-toggle="modal" data-target="#example_modal2">
            <div class="white">
              <i style="color:#AEEA98" class="icon-bullhorn"></i>
              <p style="color:#AEEA98"><%= @checked_tickets.size %></p>
            </div>
            <div class="widget">
              <input class="knob" data-width="120" data-height="120" data-displayInput=false data-readOnly=true data-thickness=".15" value="<%= @checked_tickets.size %>">   
            </div>
            <p><strong><%= @checked_tickets.size %>/<%= @root_tickets.size %></strong>Finished Tickets</p>
          </a>
        </div>
      </div>
    </div> 
    <div class="box_row clearfix">
      <div class="widget-tasks-statistics">
        <div class="userstats clearfix" style="margin-top: 25px;">
            <a href="javascript:void(0)" data-toggle="modal" data-target="#example_modal2">
            <div class="white">
              <i style="color:#98AEEA" class="icon-thumbs-up"></i>
              <p style="color:#98AEEA"></p>
            </div>
            <div class="widget">
              <input class="knob" data-width="120" data-height="120" data-displayInput=false data-readOnly=true data-thickness=".15" value="<%= @verify_latest_oder.sum(:total) %>">   
            </div>
            <p><strong><%= number_to_currency_br(@verify_latest_oder.sum(:total)) %></strong>Income In Orders</p>
          </a>
        </div>
      </div>
      <div class="widget-tasks-statistics">
        <div class="userstats clearfix" style="margin-top: 25px;">
            <a href="javascript:void(0)" data-toggle="modal" data-target="#example_modal2">
            <div class="white">
              <i style="color:#EA98AB" class="icon-credit-card"></i>
              <p style="color:#EA98AB"><%= @verify_latest_catalogs.size %></p>
            </div>
            <div class="widget">
              <input class="knob" data-width="120" data-height="120" data-displayInput=false data-readOnly=true data-thickness=".15" value="<%= @verify_latest_catalogs.size %>">   
            </div>
            <p>
              <strong><%= @verify_latest_catalogs.size %>/<%= @unverify_latest_catalogs.size %></strong>
              Catalog Items
            </p>
          </a>
        </div>
      </div>
      <div class="widget-tasks-statistics">
        <div class="userstats clearfix" style="margin-top: 25px;">
            <a href="javascript:void(0)" data-toggle="modal" data-target="#example_modal2">
            <div class="white">
              <i style="color:#F6BF99" class="icon-phone"></i>
              <p style="color:#F6BF99"><%= @verify_latest_oder.size %></p>
            </div>
            <div class="widget">
              <input class="knob" data-width="120" data-height="120" data-displayInput=false data-readOnly=true data-thickness=".15" value="<%= @verify_latest_oder.size %>">   
            </div>
            <p><strong><%= @verify_latest_oder.size %>/<%= @unverify_latest_oder.size %> </strong>Invoice Orders</p>
          </a>
        </div>
      </div>
    </div> 
  </div>
</div>

app/views/backend/shareds/home/_quick_buttons.html.erb
<div class="row-fluid">
  <div class="widget widget-padding span4">
    <div class="widget-header">
      <i class="icon-circle"></i>
      <h5>Quick Buttons</h5>
      <div class="widget-buttons">
          <a href="javascript:void(0)" class="collapse" data-collapsed="false"><i data-title="Collapse" class="icon-chevron-up"></i></a>
      </div>
    </div>
    <div class="widget-body" style="min-height: 170px;">
      <div class="row-fluid" style="margin-bottom:15px;">
        <a class="btn btn-small btn-box bubble bubble-info span4 tips" href="#" data-title="bubble-info" data-bubble="7k"><i class="icon-thumbs-up"></i><span>Likes</span></a>
        <a class="btn btn-small btn-box bubble bubble-info span4 tips" href="#" data-title="bubble-info" data-bubble="10"><i class="icon-twitter"></i><span>Tweets</span></a>
        <a class="btn btn-small btn-box span4 " href="#"><i class="icon-money"></i><span>Finance</span></a>
      </div><!-- /row-fluid -->
      <div class="row-fluid">
        <a class="btn btn-small btn-box bubble bubble-warning span4 tips" href="#" data-title="bubble-warning" data-bubble="5" style="margin-bottom:0;"><i class="icon-globe"></i><span>Region</span></a>
        <a class="btn btn-small btn-box span4 tips" href="#" data-title="" style="margin-bottom:0;"><i class="icon-search"></i><span>Search</span></a>
        <a class="btn btn-small btn-box span4 tips" href="#" data-title="" style="margin-bottom:0;"><i class="icon-cogs"></i><span>Settings</span></a>
      </div><!-- /row-fluid -->

    </div><!-- /widget-body -->
  </div><!-- /widget -->
 
  <div class="widget widget-padding span8">
    <div class="widget-header">
      <i class="icon-bar-chart"></i>
      <h5>Employee Task Status</h5>
      <div class="widget-buttons">
          <a href="javascript:void(0)" class="collapse" data-collapsed="false"><i data-title="Collapse" class="icon-chevron-up"></i></a>
      </div>
    </div>
    <div class="widget-body clearfix" style="height: 170px;" id="widget-tasks">
      <div class="widget-tasks-statistics">
        <div class="userstats clearfix" style="margin-top: 25px;">
            <a href="javascript:void(0)" data-toggle="modal" data-target="#task_modal">
            <img src="assets/avatars/07.jpg" class="image">
            <div class="widget">
              <input class="knob" data-width="75" data-height="75" data-displayInput=false data-readOnly=true data-thickness=".3" value="85">   
            </div>
            <p>Fernando</p>
          </a>
        </div>
        <div class="userstats clearfix">
            <a href="javascript:void(0)" data-toggle="modal" data-target="#task_modal">
            <img src="assets/avatars/08.jpg" class="image">
            <div class="widget">
              <input class="knob" data-width="75" data-height="75" data-displayInput=false data-readOnly=true data-thickness=".3" value="55">      
            </div>
            <p>Milagros</p>
          </a>
        </div>
        <div class="userstats clearfix">
            <a href="javascript:void(0)" data-toggle="modal" data-target="#task_modal">
            <img src="assets/avatars/09.jpg" class="image">
            <div class="widget">
              <input class="knob" data-width="75" data-height="75" data-displayInput=false data-readOnly=true data-thickness=".3" value="25">      
            </div>
            <p>Lilia</p>
          </a>
        </div>
        <div class="userstats clearfix">
            <a href="javascript:void(0)" data-toggle="modal" data-target="#task_modal">
            <img src="assets/avatars/10.jpg" class="image">
            <div class="widget">
              <input class="knob" data-width="75" data-height="75" data-displayInput=false data-readOnly=true data-thickness=".3" value="15">      
            </div>
            <p>Cody</p>
          </a>
        </div>
        <div class="userstats clearfix">
            <a href="javascript:void(0)" data-toggle="modal" data-target="#task_modal">
            <img src="assets/avatars/11.jpg" class="image">
            <div class="widget">
              <input class="knob" data-width="75" data-height="75" data-displayInput=false data-readOnly=true data-thickness=".3" value="10">      
            </div>
            <p>John</p>
          </a>
        </div>
        <div class="userstats clearfix">
            <a href="javascript:void(0)" data-toggle="modal" data-target="#task_modal">
            <img src="assets/avatars/12.jpg" class="image">
            <div class="widget">
              <input class="knob" data-width="75" data-height="75" data-displayInput=false data-readOnly=true data-thickness=".3" value="9">      
            </div>
            <p>Bryan</p>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/backend/shareds/home/_weekly_statistics.html.erb
<div class="row-fluid">
  <div class="widget span4">
    <div class="widget-header">
      <i class="icon-bar-chart"></i>
      <h5>Weekly Statistics</h5>
      <div class="widget-buttons">
          <a href="javascript:void(0)" class="collapse" data-collapsed="false"><i data-title="Collapse" class="icon-chevron-up"></i></a>
      </div>
    </div>  
    <div class="widget-body clearfix">
      <div class="widget-analytics-small">
        <ul>
          <li>
            <span class="inlinesparkline">1,5,10,5,25,30,12,22</span>
            <h5>Visits:</h5>
            <h4>502</h4>
          </li>
          <li>
            <span class="inlinesparkline">5,4,5,7,8,1,1,20,2</span>
            <h5>Unique Visitors:</h5>
            <h4>420</h4>
          </li>
          <li>
            <span class="inlinesparkline">5,3,3,98,102,155,150,187,196</span>
            <h5>Pageviews:</h5>
            <h4>2054</h4>
          </li>
          <li>
            <span class="inlinesparkline">5,44,53,66,378,771,341,520,452</span>
            <h5>Pages / Visit:</h5>
            <h4>5.8</h4>
          </li>
          <li>
            <span class="inlinesparkline">5,4,35,57,28,16,11,20,72</span>
            <h5>Avg. Visit Duration:</h5>
            <h4>00:10:34</h4>
          </li>
          <li>
            <span class="inlinesparkline">52,44,65,27,86,14,16,40,22</span>
            <h5>Bounce Rate:</h5>
            <h4>30.30%</h4>
          </li>
          <li>
            <span class="inlinesparkline">5,6,7,9,10,20,25,22,21</span>
            <h5>% New Visits:</h5>
            <h4>29.35%</h4>
          </li>
        </ul>
      </div>
    </div> <!-- /widget body -->
  </div> <!-- /widget span12 -->
  <div class="widget span8">
    <div class="widget-header">
      <i class="icon-credit-card"></i>
      <h5>Last 3 month's income</h5>
      <div class="widget-buttons">
          <button class="btn btn-info btn-small" type="button"><i class="icon-plus"></i> See more</button>
          <a href="javascript:void(0)" class="collapse" data-collapsed="false"><i data-title="Collapse" class="icon-chevron-up"></i></a>
      </div>
    </div>
    <div class="widget-body clearfix">
      <div style="height:274px;" id="graph" class="widget-analytics-large"></div>
    </div>
  </div>
</div>