config/routes.rb
Themeindo::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, 
    controllers: { 
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
      sessions: 'sessions',
      confirmations: "confirmations"
    }, 
    path_names: { 
      sign_in:  'login', 
      sign_out: 'logout', 
      sign_up:  'register' 
    }
    
  concern :startup_backend, Startup::BackendRoutes.new
  namespace :backend do
    concerns :startup_backend
  end

  concern :startup_member, Startup::MemberRoutes.new
  namespace :member do
    concerns :startup_member
  end

  root 'publics#home'
  get '/backend',                   to: 'backend#home',                     as: 'backend_home'
  get '/member',                    to: 'member#home',                      as: 'member_home'
  get '/profile',                   to: 'member#profile',                   as: 'profile'
  get 'search',                     to: 'publics#search',                   as: 'search'
  get 'portfolio/:id',              to: 'publics#portfolio',                as: 'portfolio'
  get "like/:id",                   to: "publics#upvote",                   as: 'like'
  get "document_download/:id",      to: "publics#document_download",        as: 'document_download'
  get "landing_page/:id",           to: "publics#landing_page",             as: 'landing_page'
  
  get "catalog_category_child",     to: "catalogs#catalog_category_child",  as: 'catalog_category_child'

  # Success review order
  get "review/:id",                 to: "orders#review",                    as: 'review'

  resources :catalogs do
    member do
      get 'comments'
      get 'support'
      get 'ticket'
      put "like",     to: "catalogs#upvote"
      match :upvote, path: 'like', via: [:get, :post, :put]
    end
  end

  resource :orders do
    collection do
      get :paid
      get :revoked
      post :ipn
    end
  end

  resources :order_items, only: [:create, :update, :destroy]
  resources :comments
  resources :tickets
  resources :subscribes

  # namespace :api do
  #   namespace :v1 do 
  #     resources :catalogs, only: [:index, :show] do 
  #       member do
  #         get 'comments'
  #         get 'support'
  #         get 'ticket'
  #         put "like",     to: "catalogs#upvote"
  #         match :upvote, path: 'like', via: [:get, :post, :put]
  #       end
  #     end
  #   end
  # end


end

app/controllers/backend/admins_controller.rb
class Backend::AdminsController < Backend::UsersController
	defaults resource_class: Admin, collection_name: 'admins', instance_name: 'admin'
	include Backend::ActionMultiple
	
	def index
		@collection = collection.where("id != ?", current_user.id).latest.page(page).per(per_page)
	end
end

app/controllers/backend/backend_application_controller.rb
class Backend::BackendApplicationController < Backend::ResourcesController
	layout 'backend'
	before_filter :authenticate_admin!
	protect_from_forgery with: :exception

	def authenticate_admin!
  	unless current_user.present? && (current_user.admin?)
      redirect_to root_path 
    end 
  end
end

app/controllers/backend/catalog_categories_controller.rb
class Backend::CatalogCategoriesController < Backend::BackendApplicationController
	defaults resource_class: CatalogCategory, collection_name: 'catalog_categories', instance_name: 'catalog_category'
	include Backend::ActionMultiple

	def index
		@collection = collection.latest.page(page).per(per_page)
	end

	protected
    def collection
      @collection ||= end_of_association_chain
   	end
end

app/controllers/backend/catalogs_controller.rb
class Backend::CatalogsController < Backend::BackendApplicationController
	defaults resource_class: Catalog, collection_name: 'catalogs', instance_name: 'catalog'
	include Backend::ActionMultiple
	
	def index
		@catalogs =  collection.last_updated
		@collection = @catalogs.page(page).per(per_page)

		respond_to do |format|
      format.html
      format.xls
    end
	end

	def create
		build_resource
    resource.catalog_category_id = params[:catalog_category_id]
    resource.user_id = current_user.id
    resource.save
    create! do |format|
      if resource.errors.empty?
        format.html { redirect_to backend_catalogs_path}
      else 
        flash[:errors] = resource.errors.full_messages
        format.html { redirect_to :back}
      end
    end
	end

	def update
		resource.catalog_category_id = params[:catalog_category_id]
		resource.save
		update! do |format|
      if resource.errors.empty?
        format.html { redirect_to :back}
      else 
        flash[:errors] = resource.errors.full_messages
        format.html { redirect_to :back}
      end
    end
	end

	def change_verified
		resource.change_verified_status!
		if resource.published?
			UserMailer.send_catalog_verified(resource).deliver
			redirect_to :back, notice: "#{resource.title} has verified successfully"
		else
			redirect_to :back, notice: "#{resource.title} has unverified successfully"
		end
	end

	def change_featured
		resource.change_featured_status!
		if resource.featured?
			UserMailer.send_catalog_featured(resource).deliver
			redirect_to :back, notice: "#{resource.title} has featured successfully"
		else
			redirect_to :back, notice: "#{resource.title} has unfeatured successfully"
		end
	end

	def document_download
	  @catalog = Catalog.find_by(code: params[:code])
    url = @catalog.file_catalog.url
    file_path = url.split("?").first
    if !file_path.nil?
			send_file "#{Rails.root}/public#{file_path}", :x_sendfile => true 
		else 
      redirect_to :back
		end
	end

	protected
		def collection
			@collection ||= end_of_association_chain.filter_search(params)
		end
end

app/controllers/backend/comments_controller.rb
class Backend::CommentsController < Backend::BackendApplicationController
	defaults resource_class: Comment, collection_name: 'comments', instance_name: 'comment'
	include Backend::ActionMultiple
	
	def index
		@collection = collection.roots.latest.page(page).per(per_page)
	end

	protected
		def collection
			@collection ||= end_of_association_chain
		end
end

app/controllers/backend/landing_pages_controller.rb
class Backend::LandingPagesController < Backend::BackendApplicationController
	defaults resource_class: LandingPage, collection_name: 'landing_pages', instance_name: 'landing_page'
	include Backend::ActionMultiple

	def index
		@collection = collection.latest.page(page).per(per_page)
	end

	protected
		def collection
			@collection ||= end_of_association_chain
		end
end

app/controllers/backend/members_controller.rb
class Backend::MembersController < Backend::UsersController
	defaults resource_class: Member, collection_name: 'members', instance_name: 'member'
	include Backend::ActionMultiple

	def index
		@collection = collection.latest.page(page).per(per_page)
	end

	def change_position
		resource.change_verified_status!
		if resource.staff?
			UserMailer.send_user_to_staff(resource).deliver
			redirect_to :back, notice: "#{resource.username} has change to staff successfully"
		else
			redirect_to :back, notice: "#{resource.username} has change to member successfully"
		end
	end

	def change_featured
		resource.change_featured_status!
		if resource.featured?
			UserMailer.send_user_to_featured(resource).deliver
			redirect_to :back, notice: "#{resource.username} has featured successfully"
		else
			redirect_to :back, notice: "#{resource.username} has unfeatured successfully"
		end
	end

	private
    def collection
      @members ||= end_of_association_chain.search_by(params)
    end
end

app/controllers/backend/messages_controller.rb
class Backend::MessagesController < Backend::BackendApplicationController
	defaults resource_class: Message, collection_name: 'messages', instance_name: 'message'
	include Backend::ActionMultiple
	
	def index
		@collection = collection.latest.page(page).per(per_page)
	end

	def create
		build_resource
		if params[:message][:ticket_id]
			@ticket = Ticket.find(params[:message][:ticket_id])
			@ticket.update(status: true)
			@ticket.save
		end
		resource.user_id = current_user.id
		resource.status = false
		resource.save
		create! do |format|
			if resource.errors.empty?
				UserMailer.send_reply_ticket(resource).deliver
        format.html { redirect_to :back }
      else 
        flash[:error] = 'Your Message Not Successfully Sent'
        format.html { redirect_to :back }
      end
		end
	end

	def destroy
		destroy! do |format|
			if resource.errors.empty?
        format.html { redirect_to :back }
      else 
        flash[:error] = 'Your Message Not Successfully Delete'
        format.html { redirect_to :back }
      end
		end
	end

	protected
		def collection
			@collection ||= end_of_association_chain
		end
end

app/controllers/backend/orders_controller.rb
class Backend::OrdersController < Backend::BackendApplicationController
	defaults resource_class: Order, collection_name: 'orders', instance_name: 'order'
	include Backend::ActionMultiple
	
	def index
		@collection = collection.latest.page(page).per(per_page)
	end

	def change_order_status
		@order = Order.find(params[:id])
		@order.update(order_status_id: params[:order][:order_status_id])
		if @order.save
			redirect_to :back, alert: 'Order status has changed'
		else
			redirect_to :back, error: 'Order status not changed'
		end
	end

	protected
		def collection
			@collection ||= end_of_association_chain.filter_search(params)
		end
end

app/controllers/backend/resources_controller.rb
class Backend::ResourcesController < InheritedResources::Base
	include Backend::Parameters
	
	def create
		create! do |success, failure|
			success.html { redirect_to collection_path }
		end
	end

	def update
		update! do |success, failure|
			success.html { redirect_to collection_path }
		end
	end
end

app/controllers/backend/subscribes_controller.rb
class Backend::SubscribesController < Backend::BackendApplicationController
	defaults resource_class: Subscribe, collection_name: 'subscribes', instance_name: 'subscribe'
	include Backend::ActionMultiple

	def index
		@collection = collection.latest.page(page).per(per_page)
	end

	protected
    def collection
      @collection ||= end_of_association_chain.filter_search(params)
   	end
end

app/controllers/backend/tickets_controller.rb
class Backend::TicketsController < Backend::BackendApplicationController
	defaults resource_class: Ticket, collection_name: 'tickets', instance_name: 'ticket'
	include Backend::ActionMultiple
	
	def index
		@collection = collection.latest.page(page).per(per_page)
	end

	def show
		@message = Message.new
		@messages = resource.messages.oldest
	end

	protected
		def collection
			@collection ||= end_of_association_chain.filter_search(params)
		end
end

app/controllers/backend/users_controller.rb
class Backend::UsersController < Backend::BackendApplicationController
	defaults resource_class: User, collection_name: 'users', instance_name: 'user'
	include Backend::UserFilter

	def index
		@collection = collection.page(page).per(per_page)
	end

	protected
		def collection
			@collection ||= end_of_association_chain
		end
end

app/controllers/backend/web_settings_controller.rb
class Backend::WebSettingsController < Backend::BackendApplicationController
	defaults resource_class: WebSetting, collection_name: 'web_settings', instance_name: 'web_setting'

	def index
		@collection = collection.page(page).per(per_page)
	end

	protected
		def collection
			@collection ||= end_of_association_chain
		end
end

app/controllers/backend_controller.rb
class BackendController < ApplicationController
	layout 'backend'
	before_filter :authenticate_admin!
	protect_from_forgery with: :exception

	def home
	end

	def authenticate_admin!
  	unless current_user.present? && (current_user.admin?)
      redirect_to root_path 
    end 
  end
end

app/controllers/concerns/backend/action_multiple.rb
module Backend::ActionMultiple
	extend ActiveSupport::Concern

	def action_multiple
		if params[:commit] == 'Send Subscribe'
			send_multiple_promo
		elsif params[:commit] == 'Deleted'
			destroy_multiple
		elsif params[:commit] == 'Verified'
			verified_multiple
		end	
	end

	def verified_multiple
		if params[:ids].present?
			@collection = collection.where("catalogs.id IN (?)", params[:ids])
			@collection.each do |catalog|
				catalog.change_verified_status!
				UserMailer.send_catalog_verified(catalog).deliver
			end
			redirect_to :back, notice: "You verified multiple items successfully change!"
		else
			redirect_to :back, alert: 'Please Choice Selected!'
		end
	end

	def destroy_multiple
		if params[:ids].present?
			@collection = collection.destroy(params[:ids])
			if @collection
				redirect_to :back, notice: 'Successfully Destroyed!'
			else
				redirect_to :back, alert: 'Not Successfully Destroyed!'
			end
		else
			redirect_to :back, alert: 'Please Choice Selected!'
		end
	end

	def send_multiple_promo
		if params[:ids].present?
			@collection = collection.where("catalogs.id IN (?)", params[:ids])
			subscribes = Subscribe.verified

			subscribes.each do |sub|
				catalog_ids = @collection.pluck(:id)

				catalogs = collection.where("catalogs.id IN (?)", catalog_ids)
				UserMailer.send_subscribe(sub, catalogs).deliver if catalogs.present? && subscribes.present?
			end
			redirect_to :back, notice: "You have send the email subscribes successfully!"
		else
			redirect_to :back, alert: 'Please Choice Selected!'
		end
	end
	
end

app/controllers/concerns/backend/parameters.rb
module Backend::Parameters
	extend ActiveSupport::Concern

	protected
		def permitted_params
			instance_params = params[resource_instance_name]
			params.permit(resource_instance_name => Permitable.controller(params[:controller]))
		end
end

app/views/backend/shareds/_bar_search_key.html.erb
<div class="widget widget-padding">
  <div class="filter margin-top20">
    <%= form_tag collection_path, method: 'get' do |f| %>
      <div class="row-fluid">
        <div class="widget-forms clearfix">
          <div class="control-group">
            <label class="control-label">Search Bar :</label>
            <div class="controls">
              <% if params[:controller] == 'backend/tickets' %>
                <%= select_tag :departement, options_for_select(departement, params[:departement]), prompt: 'Select Departement' %>
                <%= select_tag :priority, options_for_select(priority, params[:priority]), prompt: 'Select Priority' %>
              <% end %>
              <% if params[:controller] == 'backend/members' %>
                 <%= select_tag :staff, options_for_select(staff, params[:staff]), prompt: 'Select Type' %>
              <% end %>
              <%= text_field_tag :key, params[:key], class: "span4" %>
              <%= submit_tag :search, class: 'btn btn-primary' %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/backend/shareds/_breadcrumb.html.erb
<ul class="breadcrumb">
  <%= render_breadcrumbs :separator => ' &raquo; ' %>
</ul>

app/views/backend/shareds/_prepare_action.html.erb
<div class="btn-group">
  <a class="btn btn-small dropdown-toggle" data-toggle="dropdown" href="#">
  	Action
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu pull-right">
    <% if params[:controller] == 'backend/tickets' || params[:controller] == 'backend/orders'  %>
      <li>
        <%= link_to resource_path(resource) do %>
          <i class="icon-eye-open"></i> Show
        <% end %>
      </li>
    <% end %>

    <% unless params[:controller] == 'backend/tickets' || params[:controller] == 'backend/orders' %>
      <li>
      	<%= link_to edit_resource_path(resource) do %>
      		<i class="icon-edit"></i> Edit
      	<% end %>
      </li>
      <li>
      	<%= link_to resource_path(resource), method: 'delete', data: {confirm: confirmation} do %>
      		<i class="icon-trash"></i> Delete
      	<% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/backend/shareds/_prepare_form.html.erb
<div class="row-fluid">
  <%= render 'backend/shareds/breadcrumb' %>
  <h2 class="heading">
    <%= "#{action_name} #{form_name}" %>
    <div class="btn-group pull-right">
      <%= link_to new_resource_path do %>
        <button class="btn"><i class="icon-pencil"></i> Create New</button>
      <% end %>
      <%= link_to collection_path do %>
        <button class="btn"><i class="icon-list-alt"></i> List</button>
      <% end %>
      <button class="btn" type="submit" class="btn btn-sm btn-danger pull-right">
        <i class="icon-trash"></i> Delete selected
      </button>
    </div>
  </h2>
</div>

<div class="widget widget-padding">
  <div class="widget-header">
    <i class="icon-bookmark"></i>
    <h5><%= "#{action_name} #{form_name}" %></h5>
    <div class="widget-buttons">
      <a href="#" data-title="Collapse" data-collapsed="false" class="collapse">
        <i class="icon-chevron-up"></i>
      </a>
    </div>
  </div>
  <%= form_for [:backend, resource ], method: form_method, html: {class: 'form-horizontal'} do |f| %>
    <div class="widget-body">
      <%= render partial: 'form', locals: { f: f } %>
    </div>
    <div class="widget-footer">
      <button class="btn btn-primary" type="submit">Save</button>
    </div>
  <% end %>
</div>

app/views/backend/shareds/_prepare_table.html.erb
<div class="row-fluid">
  <%= render 'backend/shareds/breadcrumb' %>
  <h2 class="heading">
    <%= table_name %>
    <div class="btn-group pull-right">
      <%= link_to new_resource_path do %>
        <span class="btn"><i class="icon-pencil"></i> Create New</span>
      <% end %>
      <%= link_to collection_path do %>
        <span class="btn"><i class="icon-list-alt"></i> List</span>
      <% end %>
      <% if params[:controller] == 'backend/catalogs' %>
        <button type="submit" class="btn btn-sm btn-primary pull-right" name="commit" value="Send Subscribe">
          <i class="icon-envelope"></i> Send Email Subscribe Promo
        </button>
        <button type="submit" class="btn btn-sm btn-success pull-right" name="commit" value="Verified">
          <i class="icon-ok"></i> Verified Selected
        </button>
        <%= link_to collection_path(format: "xls") do %>
          <div class="btn btn-sm btn-info pull-right">
            <i class="icon-bookmark"></i> Export
          </div>
        <% end %>
      <% end %>
      <button type="submit" class="btn" name="commit" value="Deleted">
        <i class="icon-trash"></i> Delete Selected
      </button>
    </div>
  </h2>
</div>

<div class="widget widget-padding">
  <div class="widget-header">
    <i class="icon-list-alt"></i>
    <h5><%= table_name %></h5>
    <div class="widget-buttons">
      <a href="#" data-title="Collapse" data-collapsed="false" class="collapse">
        <i class="icon-chevron-up"></i>
      </a>
    </div>
  </div>

app/views/backend/shareds/_prepare_table_member.html.erb
<h2 class="margin-top0">
  <div class="row">
    <div class="col-md-4">
      <%= table_name %>
    </div>
    <div class="col-md-8">
      <div class="btn-group float-right">
        <% if params[:controller] == 'member/catalogs' %>
          <button type="submit" class="btn btn-sm btn-primary" name="commit" value="Send Subscribe">
            <i class="fa fa-envelope-o"></i> Send Email Subscribe Promo
          </button>
        <% end %>
        <% unless params[:controller] == 'member/tickets' || params[:controller] == 'member/catalogs' %>
          <button type="submit" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i> Delete selected</button>
        <% end %>
        <%= link_to new_resource_path, class: "btn btn-info btn-sm" do %> 
          <i class="fa fa-plus-circle"></i> <%= table_name %> New
        <% end %>
      </div>
    </div>
  </div>
</h2>

app/views/backend/shareds/_side_left.html.erb
<div class="sidebar-nav nav-collapse collapse">
  <div class="user_side clearfix">
    <%= image_tag current_user.try(:profile).try(:avatar).url(:small) %>
    <h5><%= current_user.username %></h5>
    <%= link_to edit_backend_admin_path(current_user) do %>
      <i class="icon-cog"></i> Settings
    <% end %>  
  </div>
  <div class="accordion" id="accordion2">
    <div class="accordion-group">
      <div class="accordion-heading">
        <%= link_to backend_home_path, class: "accordion-toggle b_F79999" do %>
          <i class="icon-dashboard"></i> Dashboard
        <% end %>
      </div>
    </div>
    <div class="accordion-group">
      <div class="accordion-heading">
        <a class="accordion-toggle b_C3F7A7 collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapse1"><i class="icon-group"></i> Users Managements</a>
      </div>
      <div id="collapse1" class="accordion-body collapse">
        <div class="accordion-inner">
          <%= link_to backend_admins_path, class: "accordion-toggle #{active_sidebar?(:admins, :all)}" do %>
            <i class="icon-file-alt"></i> Admins
          <% end %>
          <%= link_to backend_members_path, class: "accordion-toggle #{active_sidebar?(:members, :all)}" do %>
            <i class="icon-file-alt"></i> Members
          <% end %>
        </div>
      </div>
    </div>
    <div class="accordion-group">
      <div class="accordion-heading">
        <a class="accordion-toggle b_C3F7A7 collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapse2"><i class="icon-bookmark"></i> Catalogs</a>
      </div>
      <div id="collapse2" class="accordion-body collapse">
        <div class="accordion-inner">
          <%= link_to new_backend_catalog_path, class: "accordion-toggle #{active_sidebar?(:catalogs, :new)}" do %>
            <i class=" icon-pencil"></i> Create New
          <% end %>
          <%= link_to backend_catalogs_path, class: "accordion-toggle #{active_sidebar?(:catalogs, :all)}" do %>
            <i class="icon-file-alt"></i> List Catalogs
          <% end %>
          <%= link_to backend_catalog_categories_path, class: "accordion-toggle #{active_sidebar?(:catalog_categories, :all)}" do %>
            <i class="icon-file-alt"></i> List Categories
          <% end %>
        </div>
      </div>
    </div>
    <div class="accordion-group">
      <div class="accordion-heading">
        <%= link_to backend_orders_path, class: "accordion-toggle b_F5C294 #{active_sidebar?(:orders, :all)}" do %>
          <i class=" icon-list-alt"></i> Invoice Order
        <% end %>
      </div>
    </div>  
    <div class="accordion-group">
      <div class="accordion-heading">
        <%= link_to backend_tickets_path, class: "accordion-toggle b_F5C294 #{active_sidebar?(:tickets, :all)}" do %>
          <i class="icon-credit-card"></i> Tickets
        <% end %>
      </div>
    </div>  
    <div class="accordion-group">
      <div class="accordion-heading">
        <%= link_to backend_comments_path, class: "accordion-toggle b_F5C294 #{active_sidebar?(:comments, :all)}" do %>
          <i class="icon-comments"></i> Comments
        <% end %>
      </div>
    </div>
    <div class="accordion-group">
      <div class="accordion-heading">
        <%= link_to backend_subscribes_path, class: "accordion-toggle b_F5C294 #{active_sidebar?(:subscribes, :all)}" do %>
          <i class="icon-user"></i> Subscribes
        <% end %>
      </div>
    </div>
    <div class="accordion-group">
      <div class="accordion-heading">
        <a class="accordion-toggle b_C3F7A7 collapsed" data-toggle="collapse" data-parent="#accordion3" href="#collapse3">
          <i class="icon-file-alt"></i> Landing Pages
        </a>
      </div>
      <div id="collapse3" class="accordion-body collapse">
        <div class="accordion-inner">
          <%= link_to new_backend_landing_page_path, class: "accordion-toggle #{active_sidebar?(:landing_pages, :new)}" do %>
            <i class=" icon-pencil"></i> Create New
          <% end %>
          <%= link_to backend_landing_pages_path, class: "accordion-toggle #{active_sidebar?(:landing_pages, :all)}" do %>
            <i class="icon-file-alt"></i> List Landing Pages
          <% end %>
        </div>
      </div>
    </div>
    <div class="accordion-group">
      <div class="accordion-heading">
        <%= link_to backend_web_settings_path, class: "accordion-toggle b_F5C294 #{active_sidebar?(:web_settings, :all)}" do %>
          <i class="icon-cogs"></i> Settings
        <% end %>
      </div>
    </div>      
  </div>
</div>
<!-- /Side menu -->

app/views/backend/shareds/_top_menu.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <div class="logo"> 
        <%= link_to backend_home_path do %>
          <%= image_tag @setting.logo.url(:small), style: "height: 35px;" %>
        <% end %>
      </div>
       <a class="btn btn-navbar visible-phone" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
       <a class="btn btn-navbar slide_menu_left visible-tablet">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <div class="top-menu visible-desktop">
        <ul class="pull-left">
          <li>
            <a id="messages" data-notification="<%= @latest_tickets.size %>" href="#">
              <i class="icon-envelope"></i> Tickets</a>
            </li>
          <li>
            <a id="notifications" data-notification="<%= @latest_comments.size %>" href="#">
              <i class="icon-globe"></i> Notifications
            </a>
          </li>
        </ul>
        <ul class="pull-right">
          <li>
            <%= link_to '<i class="icon-wrench"></i>Settings'.html_safe, edit_backend_admin_path(current_user) %>
          </li>
          <li>
            <%= link_to '<i class="icon-off"></i>LogOut'.html_safe, destroy_user_session_path, method: 'delete' %></a>
          </li>
        </ul>
      </div>

      <div class="top-menu visible-phone visible-tablet">
        <ul class="pull-right">  
          <li>
            <a title="link to View all Messages page, no popover in phone view or tablet" href="#">
              <i class="icon-envelope"></i>
            </a>
          </li>
          <li>
            <a title="link to View all Notifications page, no popover in phone view or tablet" href="#">
              <i class="icon-globe"></i>
            </a>
          </li>
          <li><a href="login.html"><i class="icon-off"></i></a></li>
        </ul>
      </div>

    </div>
  </div>
</div>