config/routes.rb
Themeindo::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, 
    controllers: { 
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
      sessions: 'sessions',
      confirmations: "confirmations"
    }, 
    path_names: { 
      sign_in:  'login', 
      sign_out: 'logout', 
      sign_up:  'register' 
    }
    
  concern :startup_backend, Startup::BackendRoutes.new
  namespace :backend do
    concerns :startup_backend
  end

  concern :startup_member, Startup::MemberRoutes.new
  namespace :member do
    concerns :startup_member
  end

  root 'publics#home'
  get '/backend',                   to: 'backend#home',                     as: 'backend_home'
  get '/member',                    to: 'member#home',                      as: 'member_home'
  get '/profile',                   to: 'member#profile',                   as: 'profile'
  get 'search',                     to: 'publics#search',                   as: 'search'
  get 'portfolio/:id',              to: 'publics#portfolio',                as: 'portfolio'
  get "like/:id",                   to: "publics#upvote",                   as: 'like'
  get "document_download/:id",      to: "publics#document_download",        as: 'document_download'
  get "landing_page/:id",           to: "publics#landing_page",             as: 'landing_page'
  
  get "catalog_category_child",     to: "catalogs#catalog_category_child",  as: 'catalog_category_child'

  # Success review order
  get "review/:id",                 to: "orders#review",                    as: 'review'

  resources :catalogs do
    member do
      get 'comments'
      get 'support'
      get 'ticket'
      put "like",     to: "catalogs#upvote"
      match :upvote, path: 'like', via: [:get, :post, :put]
    end
  end

  resource :orders do
    collection do
      get :paid
      get :revoked
      post :ipn
    end
  end

  resources :order_items, only: [:create, :update, :destroy]
  resources :comments
  resources :tickets
  resources :subscribes

  # namespace :api do
  #   namespace :v1 do 
  #     resources :catalogs, only: [:index, :show] do 
  #       member do
  #         get 'comments'
  #         get 'support'
  #         get 'ticket'
  #         put "like",     to: "catalogs#upvote"
  #         match :upvote, path: 'like', via: [:get, :post, :put]
  #       end
  #     end
  #   end
  # end


end

app/views/shareds/_author_featured.html.erb
<div class="row">
	<div class="col-md-12 col-xs-12">
		<h2>Featured Author</h2>
	</div>
	<div class="col-md-6 col-xs-12">
		<div class="col-xs-2 avatar-responsive padding-left0">
			<%= image_tag @featured_author.try(:profile).try(:avatar).url(:small), class: 'full-width' %>
		</div>
		<div class="col-xs-10">
			<p>
				This week's featured author is
				<%= link_to portfolio_path(@featured_author.username) do %>
					<%= @featured_author.try(:profile).try(:full_name).try(:titleize) %>
				<% end %>
			</p>
			<%= link_to 'View Portfolio', portfolio_path(@featured_author.username), class: "btn btn-info" %>
		</div>
	</div>
	<div class="col-md-6 col-xs-12">
		<div class="row margin0 item-on-profile">
			<div class="featured-section-author-featured">
				<% @verify_featured_author.limit(4).each do |resource| %>
					<% cache ["verify_featured_author_catalogs_#{resource.id}_#{resource.updated_at.to_time.to_i}"] do %>
						<div class="col-xs-2 latest-user-item float-right" data-toggle="popover" title="<%= truncate(strip_tags(resource.title.to_s), length: 40, omission: ' ...') %>">
			        <div class="tooltips-content">
			          <div class="tooltips-image">
			            <%= image_tag resource.try(:galleries).try(:oldest).try(:first).try(:file).url(:medium) %>
			          </div>
			          <div class="tooltips-desc">
			            <%= rating_for resource, "price", :star => 5 %>
			          </div>
			          <span class="tooltips-tag">
			            <%= resource.try(:catalog_category_root).try(:name).titleize %>,
			            <%= resource.try(:catalog_category_child).try(:name).titleize %>
			          </span>
			          <span class="tooltips-price"><%= number_to_currency_br(resource.try(:price)) %></span>
			        </div>
			        <%= link_to catalog_path(resource), class: "po-image avatar-responsive" do %>
			          <%= image_tag resource.try(:thumbnail).url(:small) %>
			        <% end %>
			      </div>
			    <% end %>
				<% end if @verify_featured_author.present? %>
			</div>
		</div>
		<span class="float-right">
			Some of
			<%= link_to portfolio_path(@featured_author.username) do %>
				<%= @featured_author.try(:profile).try(:full_name).try(:titleize) %>
			<% end %>
			work
		</span>
	</div>
</div>

app/views/shareds/_breadcrumb.html.erb
<div class="col-md-12">
	<div class="breadcrumb-step">
		<%= render_breadcrumbs :separator => ' &raquo; ' %>
	</div>
</div>

app/views/shareds/_featured.html.erb
<!-- Services Section -->
	<section id="featured" class="grey">
		<h1>Featured</h1>
		<div class="hr dark"></div>
		<p class="desc-section-p"><%#= @featureds.size %> Best Available Template Design Choices Our Team</p>
		<div class="container">
			<div class="row item-on-profile">
				<div class="featured-section">
					<% @featureds.each do |resource| %>
						<% cache ["featured_catalogs_#{resource.id}_#{resource.updated_at.to_time.to_i}"] do %>
							<div class="col-xs-2 latest-user-item" data-toggle="popover" title="<%= truncate(strip_tags(resource.title.to_s), length: 40, omission: ' ...') %>">
				        <div class="tooltips-content">
				          <div class="tooltips-image">
				            <%= image_tag resource.try(:galleries).try(:oldest).try(:first).try(:file).url(:medium) %>
				          </div>
				          <div class="tooltips-desc">
				            <%= rating_for resource, "price", :star => 5 %>
				          </div>
				          <span class="tooltips-tag">
				            <%= resource.try(:catalog_category_root).try(:name).titleize %>,
				            <%= resource.try(:catalog_category_child).try(:name).titleize %>
				          </span>
				          <span class="tooltips-price"><%= number_to_currency_br(resource.try(:price)) %></span>
				        </div>
				        <%= link_to catalog_path(resource), class: "po-image avatar-responsive" do %>
				          <%= image_tag resource.try(:thumbnail).url(:small) %>
				        <% end %>
				      </div>
				    <% end %>
					<% end %>
					<div class="col-xs-12 wrap-featured-button">
						<%= link_to search_path(params.merge(featured: true)) do %>
							<button class="btn btn-success">View more featured item</button>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</section>
<!-- /Services Section -->

app/views/shareds/_flash_errors.html.erb
<div class="alert alert-warning alert-dismissible" role="alert">
  <button class="close" data-dismiss="alert">
    <span aria-hidden="true">×</span>
    <span class="sr-only">Close</span>
  </button> <%= note %>
</div>

app/views/shareds/_footer.html.erb
<footer class="footer col-xs-12">
	<div class="container">
		<div class="row">
      <div class="col-md-2">
        <div class="follow-us">
          <h3>FOLLOW US</h3>
          <a href="<%= @setting.try(:facebook) %>" class="btn site-facebook"><i class="fa fa-facebook"></i></a>
          <a href="<%= @setting.try(:twitter) %>" class="btn site-twitter"><i class="fa fa-twitter"></i></a>
          <a href="mailto:<%= @setting.try(:email) %>" class="btn site-google-plus"><i class="fa fa-google-plus"></i></a>
        </div>
      </div>
      <div class="col-md-7">
        <div class="row">
          <div class="col-md-4 footer-help">
            <h3>ABOUT</h3>
            <ul class="footer-box-list">
              <li>
                <%= link_to "About Themeindo", landing_page_path('About Themeindo') %>
              </li>
              <li>
                <%= link_to "Themeindo Market Terms", landing_page_path('Themeindo Market Terms') %>
              </li>
              <li>
                <%#= link_to "Author Terms", landing_page_path('Author Terms') %>
              </li>
              <li>
                <%= link_to "Privacy Policy", landing_page_path('Privacy Policy') %>
              </li>
            </ul>
          </div>
          <div class="col-md-8 footer-info">
            <h3><%= @setting.title %></h3>
            <%= @setting.description %>
          </div>
        </div>
      </div>
      <div class="col-md-3 footer-subscribe">
        <h3>SUBSCRIBE</h3>
        <div class="form-group">
          <%= form_for Subscribe.new, url: subscribes_path, method: 'post' do |f| %>
            <%= f.email_field :email, class: "form-control", placeholder: "Email", required: true %>
            <%= submit_tag :subscibe, class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-xs-12">
        <p>&copy; <%= @setting.try(:footer_tags) %>
        <%= image_tag 'paypal.png', class: 'float-right margin-top10' %>
        </p>
      </div>
    </div>
	</div>
</section>

<%= render "shareds/sign" %>

<a href="#" class="scrollup">
  <i class="fa fa-chevron-up"></i> 
</a>

app/views/shareds/_form_top_search.html.erb
<% unless params[:controller].match('/tickets') %>
  <div class="input-group-btn search-front">
    <button type="button" class="btn btn-lg btn-default dropdown-toggle" data-toggle="dropdown">
      <span id="search_concept">All</span> &nbsp;<span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
      <% catalog_category_root.each do |c| %>
        <li><a href="#<%= c.name.titleize %>"><%= c.name.titleize %></a></li>
      <% end %>

    </ul>
  </div>
  <% value_catalog_type = params[:catalog_category_type].present? ? params[:catalog_category_type] : '' %>
  <%= hidden_field_tag :catalog_category_type, nil, id: "search_param", value: value_catalog_type %>
<% end %>

<% value_title = params[:title].present? ? params[:title] : '' %>
<%= text_field_tag :title, nil, class: 'input-lg form-control', placeholder: 'Search..', value: value_title %>
<span class="input-group-btn">
  <button class="btn btn-lg btn-info" type="submit">
  	<span class="glyphicon glyphicon-search"></span>
  </button>
</span>
  

app/views/shareds/_latest_catalog.html.erb
<section class="grey">
  <div class="container">
    <h1>New Items</h1>
    <div class="hr dark"></div>
    <p class="desc-section-p">
      Below is a collection of some of the latest items in themeindo
    </p>
    <section id="pinBoot">
      <% @latest_catalogs.each_with_index do |resource, index| %>
        <% cache ["latest_catalogs_#{resource.id}_#{resource.updated_at.to_time.to_i}"] do %>
          <article class="white-panel">
            <%= image_tag resource.galleries.oldest.first.file.url(:small), class: 'full-width' %>
            <h4>
              <%= link_to catalog_path(resource) do %>
                <%= resource.title.to_s %>
              <% end %>
            </h4>
            <div class="row">
              <div class="col-xs-6">
                <span class="price-list">
                  <%= rating_for resource, "price", :star => 5 %>
                </span>
              </div>
              <div class="col-xs-6">
                <span class="small color-grey pull-right">
                  <i class="fa fa-tags"></i>
                  <%= resource.try(:catalog_category_root).try(:name).titleize %>
                </span>
              </div>
            </div>
            <div class="">
              <div class="col-xs-12 content-bottom">
                <span class="btn pull-left">
                  <%= resource.score %> <i class="fa fa-thumbs-up"></i>
                </span>
                <span class="btn pull-left">
                  <%= resource.impressionist_count %> <i class="fa fa-eye"></i>
                </span>
                <span class="price-grid-list pull-right">
                  <%= number_to_currency_br(resource.try(:price)) %>
                </span>
              </div>
            </div>
          </article>
        <% end %>
      <% end %>
    </section>
    <hr>
  </div>
</section>

app/views/shareds/_load.html.erb
<div class="loading">
	<%= x_image_tag @setting.logo.url(:medium), class: 'logo-load' if @setting.logo.present? %>
</div>

app/views/shareds/_services.html.erb
<!-- Services Section -->
	<section class="services">
		<h1>How does it work ?</h1>
		<div class="hr dark"></div>
		<p class="desc-section-p">
			Below is the explanation steps on how to buy items on Themeindo Market.
		</p>
		<div class="container">
			<div class="row">
				<div class="col-xs-12 col-sm-6 col-md-3">
					<div class="box">
						<div class="box-icon">
							<span class="fa fa-4x fa-hand-o-up"></span>
						</div>
						<div class="info">
							<h4 class="text-center">Choice Your Item</h4>
							<p>look on our impressive collections and choose your desired item.</p>
						</div>
					</div>
				</div>

				<div class="col-xs-12 col-sm-6 col-md-3">
					<div class="box">
						<div class="box-icon">
							<span class="fa fa-4x fa-shopping-cart"></span>
						</div>
						<div class="info">
							<h4 class="text-center">Add To Cart Your Item</h4>
							<p>Add your desired item to your shopping cart</p>
						</div>
					</div>
				</div>

				<div class="col-xs-12 col-sm-6 col-md-3">
					<div class="box">
						<div class="box-icon">
							<span class="fa fa-4x fa-money"></span>
						</div>
						<div class="info">
							<h4 class="text-center">Make a Payment Your Items</h4>
							<p>Complete the payment for the items that you order.</p>
						</div>
					</div>
				</div>

				<div class="col-xs-12 col-sm-6 col-md-3">
					<div class="box">
						<div class="box-icon">
							<span class="fa fa-4x fa-cloud-download"></span>
						</div>
						<div class="info">
							<h4 class="text-center">Download Your Item</h4>
							<p>Congratulations! your item is ready to download!</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- /Services Section -->

app/views/shareds/_sign.html.erb
<div class="modal fade bs-modal-sm" id="myModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header bg-sky modal-header-info">
        <h3 align="center">SignIn</h3>
      </div>
      <div class="modal-body modal-sign">
        <%= form_for :user, url: user_session_path, method: 'post', html: {class: ""} do |f| %>
          <fieldset>
            <div class="form-group">
              <%= link_to user_omniauth_authorize_path(:facebook), class: 'btn btn-primary-fb' do %>
                <i class="fa fa-facebook pull-left"></i>
                Login With Facebook
              <% end %>
            </div>
            <div class="form-group">
              <div class="col-xs-12 or-section">
                <i class="omb-or"></i>
                <span class="omb-span">OR</span>
              </div>
            </div>
            <div class="form-group">
              <div class="controls">
                <%= f.text_field :login, class: "form-control", placeholder: "Username or Email" %>
              </div>
            </div>

            <!-- Password input-->
            <div class="form-group">
              <div class="controls">
                <%= f.password_field :password, class: "form-control password", placeholder: "Password" %>
              </div>
            </div>

            <div class="row">
              <div class="col-md-12">
                <%= f.check_box :remember_me, class: "grey remember" %>
                <span>Keep me signed in</span>
              </div>
              
              <div class="col-md-12">
                <div class="form-group">
                  <div class="controls">
                    <%= f.submit 'SignIn',  class: "btn btn-lg btn-primary btn-block" %>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                Not Member? 
                <a href="#signup" data-dismiss="modal" data-toggle="modal" data-target=".bs-modal-sm2">
                  Register
                </a> 
              </div>
              <div class="col-md-6">
                <%= link_to 'Forgot Password ?', new_user_password_path %>
              </div>
            </div>
          </fieldset>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade bs-modal-sm2" id="myModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header modal-header-info">
        <h3 align="center">Register</h3>
      </div>
      <div class="modal-body modal-sign">
        <%= form_for :user, url: user_registration_path, method: 'post', html: {class: "form-horizontal"} do |f| %>
          <%= f.fields_for(:profile_attributes) do |profile| %>
            <fieldset>
              <div class="form-group">
                <%= link_to user_omniauth_authorize_path(:facebook), class: 'btn btn-primary-fb' do %>
                  <i class="fa fa-facebook pull-left"></i>
                  Register With Facebook
                <% end %>
              </div>
              <div class="form-group">
                <div class="col-xs-12 or-section">
                  <i class="omb-or"></i>
                  <span class="omb-span">OR</span>
                </div>
              </div>
              
              <div class="form-group">
                <label class="control-label" for="userid">Fullname:</label>
                <div class="controls">
                  <%= profile.text_field :full_name, class: "form-control", required: true %>
                </div>
              </div>

              <div class="form-group">
                <label class="control-label" for="userid">Username:</label>
                <div class="controls">
                  <%= f.text_field :username, class: "form-control", required: true %>
                </div>
              </div>

              <div class="form-group">
                <label class="control-label" for="Email">Email:</label>
                <div class="controls">
                  <%= f.email_field :email, class: "form-control", required: true %>
                </div>
              </div>

              <!-- Password input-->
              <div class="form-group">
                <label class="control-label" for="password">Password:</label>
                <div class="controls">
                  <%= f.password_field :password, class: "form-control password", required: true %>
                </div>
              </div>

              <!-- Text input-->
              <div class="form-group">
                <label class="control-label" for="reenterpassword">Password Confirmation:</label>
                <div class="controls">
                  <%= f.password_field :password_confirmation, class: "form-control password", required: true %>
                </div>
              </div>

              <div class="row">
                <div class="col-md-12">
                  <label class="control-label" for="confirmsignup"></label>
                  <div class="controls">
                    <%= f.submit 'SignUp', class: "btn btn-lg btn-primary btn-block btn-success" do%>
                    <% end %>
                  </div>
                </div>

                <div class="col-md-12 margin-top10">
                  <div class="margin-auto-display-table">
                    Already Registered? 
                    <a href="#signin" data-dismiss="modal" data-toggle="modal" data-target=".bs-modal-sm">
                      Login
                    </a> 
                  </div>
                </div>
              </div>
            </fieldset>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shareds/_testimonial.html.erb
<div class="modal fade modal-testimonial" id="modal-testimonial" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-md">
		<div class="modal-content">
			<div class="modal-header bg-sky modal-header-info">
				<h3 align="center">
					Submit Testimonial
				</h3>
			</div>
			<div class="modal-body">
				<div class="row" id="post-review-box">
					<div class="col-md-12">
						<div class="col-xs-2 padding-left0">
							<img alt="" src="//myinstantcms.ru/images/img15.png">
						</div>
						<div class="col-xs-10 padding-right0">
							<input id="ratings-hidden" name="rating" type="hidden">
							
							<h3 class="margin-bottom0">
								<a href="./member">
									John doe
								</a>
							</h3>
							<h5>
								Jakarta, Indonesia
							</h5>
						</div>
						<textarea class="form-control animated" cols="50" name="testimonial" placeholder="Enter your review here..." rows="5">
						</textarea>
						<div class="text-left">
							<div class="starrr testimonial-rating-field" data-rating="0">
							</div>
							<button class="btn btn-success" type="submit">
								Submit
							</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="modal fade modal-confirm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-header">
				<h5 align="center">
					Are you sure?
				</h5>
			</div>
			<div class="modal-body">
				<div class="row" id="post-review-box">
					<div class="display-table-auto">
						<a href="#" class="btn btn-success margin-right10" type="submit">
							Yes
						</a>
						<a href="#" class="btn btn-default" data-dismiss="modal" type="submit">
							No
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="carousel-testimonial broun-block">
	<div class="container">
		<div class="row">
			<h1 class="section-main-title">
				Featured Items
			</h1>
			<p class="desc-main-title">
				1,290 Professional Corporate Website Templates
				<a href="#" data-toggle="modal" data-target=".modal-testimonial">
					give testimonial
				</a>
				| 
				<a href="#" data-toggle="modal" data-target=".modal-confirm">
					test confirm alert
				</a>
			</p>
			<div id="carousel-reviews" class="home-testimonial carousel slide" data-ride="carousel">
				<div class="carousel-inner">
					<% @featureds.each do |resource| %>
						<div class="testimonial-item col-md-4 col-sm-6">
							<div class="block-text rel zmin">
								<h3>
									<%= link_to catalog_path(resource) do %>
										<%= truncate(strip_tags(resource.title.to_s), length: 40, omission: ' ...') %>
									<% end %>
								</h3>
								<div class="image-testimonial col-xs-12 padding0">
									<%= image_tag resource.try(:galleries).try(:oldest).try(:first).try(:file).url(:medium), class: 'full-width' %>
								</div>
                <h5 class="likes-grid-list">
                  <span class="label label-warning pull-right">
                    <%= resource.score %> <i class="fa fa-thumbs-up"></i>
                  </span>
                  <span class="label label-warning pull-right">
                    <%= resource.impressionist_count %> <i class="fa fa-eye"></i>
                  </span>
                  <%= rating_for resource, "price", :star => 5 %>
                </h5>
                <ul class="tag-catalog">
                  <li><%= resource.try(:catalog_type).titleize %></li>
                  <li>, <%= resource.try(:catalog_category).try(:name).titleize %></li>
                </ul>
							</div>
						</div>
					<% end %>
				</div>
				<a class="left carousel-control" href="#carousel-reviews" role="button" data-slide="prev">
					<span class="glyphicon glyphicon-chevron-left">
					</span>
				</a>
				<a class="right carousel-control" href="#carousel-reviews" role="button" data-slide="next">
					<span class="glyphicon glyphicon-chevron-right">
					</span>
				</a>
			</div>
		</div>
	</div>
</div>

app/views/shareds/_top_menu.html.erb
<!-- Top Bar -->
<div class="top-bar">
  <div class="container">
    <div class="col-md-4 col-sm-6 col-xs-12">
      <span class="welcome-message">Welcome To Themeindo Market</span>
    </div>
    <div class="col-md-8 col-sm-6 col-xs-12">
      <ul class="nav navbar-nav navbar-right nav-account">
        <li>
          <% unless current_user %>
            <div class="btn-group login-reg-actions">
              <%= link_to 'Create an Themeindo Account', new_user_registration_path, class: "btn nav-login create-account" %>
              <div class="cart-text btn cart-btn">
                <%= render 'layouts/cart_text' %>
              </div>
              <a href="#signin" data-toggle="modal" data-target=".bs-modal-sm" class="btn nav-register"> Sign In </a>
            </div>
          <% else %>
            <div class="btn-group login-reg-actions" role="group">
              <div class="btn nav-login create-account dropdown user-menu-dropdown">
                <a class="dropdown-toggle logged" data-toggle="dropdown">
                  <i class="fa fa-user"></i>&nbsp; <%= current_user.email %> &nbsp;<i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <%= link_to member_home_path do %>
                      Home <i class="fa fa-home fa-1 pull-right"></i>
                    <% end %>
                  </li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to profile_path do %>
                      Profile <i class="fa fa-user pull-right"></i>
                    <% end %>
                  </li>
                  <li class="divider"></li>
                  <% if current_user.staff? %>
                    <li>
                      <%= link_to member_catalogs_path do %>
                        My Items <i class="fa fa-list-ul pull-right"></i>
                      <% end %>
                    </li>
                    <li class="divider"></li>
                  <% end %>
                  <li>
                    <%= link_to member_orders_path do %>
                      Invoice Orders
                      <i class="fa fa-shopping-cart pull-right"></i>
                    <% end %>
                  </li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to member_favorites_path do %>
                      Favorites <i class="fa fa-heart pull-right"></i>
                    <% end %>
                  </li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to edit_member_member_path(current_user) do %>
                      Account Settings <i class="fa fa-wrench pull-right"></i>
                    <% end %>
                  </li>
                  <li class="divider"></li>
                  <li class="text-right">
                    <%= link_to destroy_user_session_path, method: 'delete' do %>
                      Log Out
                    <% end %>
                  </li>
                </ul>
              </div>
              <% if @latest_messages.present? %>
                <div class="btn dropdown menu-notification">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" >
                    <span class="label label-danger"><%= @latest_messages.size %></span>
                    <i class="fa fa-envelope"></i>
                    <i class="fa fa-caret-down"></i>
                  </a>
                  <ul class="dropdown-menu dropdown-notification">
                    <% @latest_messages.each do |resource| %>
                      <li>
                        <%= link_to member_message_path(resource) do %>
                          <div class="content-notification">
                            <div class="photo-notification pull-left">
                              <%= image_tag resource.try(:user).try(:profile).try(:avatar).url(:small) %>
                            </div>
                            <span class="color-blue float-left">
                              <%= resource.try(:user).try(:username) %>
                            </span>
                            <span class="date-notification">
                              <%= resource.try(:created_at).strftime("%H:%M %B, %d, %Y") %>
                            </span>
                            <%= link_to member_message_path(resource) do %>
                              <p class="msg-content small"><%= truncate resource.try(:subject), length: 30 %></p>
                            <% end %>
                          </div>
                        <% end %>
                      </li>
                    <% end %>
                    <li class="view-all-notification text-center">
                      <%= link_to 'View all message', member_messages_path %>
                    </li>
                </div>
              <% end %>
              <div class="cart-text btn cart-btn">
                <%= render 'layouts/cart_text' %>
              </div>
              <%= link_to destroy_user_session_path, method: 'delete', class: 'btn' do %>
                Sign Out
              <% end %>
            </div>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>
<!-- /Top Bar -->

<!-- Top Navigation -->
<div id="top-navigation">
  <nav class="navbar-default" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-megadropdown-tabs">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path, class: "navbar-brand" do %>
          <%= image_tag @setting.logo.url(:medium) %>
        <% end %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
        <ul class="nav navbar-nav top-menu">
          <li>
            <%= link_to "All", catalogs_path %>
          </li>
          <% if Rails.cache.exist?('catalog_categories_latest') %>
            <% Rails.cache.read('catalog_categories_latest').each_with_index do |resource, index| %>
              <li class="dropdown">
                <a data-toggle="dropdown" href="#" class="dropdown-toggle">
                  <%= resource.name %> <i class="fa fa-angle-double-down"></i>
                </a>
                <ul class="dropdown-menu list-dropdown-menu">
                  <% resource.children.alfa.each do |resource| %>
                    <li>
                      <%= link_to "<span>#{resource.name}</span> <span class='pull-right bold'>#{resource.catalogs.verify.size}</span>".html_safe,
                                search_path(params.merge(catalog_category: resource.name)),
                                method: 'get' %>
                    </li>
                  <% end %>
                </ul>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</div>
<!-- /Top Navigation -->