config/routes.rb
Themeindo::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, 
    controllers: { 
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
      sessions: 'sessions',
      confirmations: "confirmations"
    }, 
    path_names: { 
      sign_in:  'login', 
      sign_out: 'logout', 
      sign_up:  'register' 
    }
    
  concern :startup_backend, Startup::BackendRoutes.new
  namespace :backend do
    concerns :startup_backend
  end

  concern :startup_member, Startup::MemberRoutes.new
  namespace :member do
    concerns :startup_member
  end

  root 'publics#home'
  get '/backend',                   to: 'backend#home',                     as: 'backend_home'
  get '/member',                    to: 'member#home',                      as: 'member_home'
  get '/profile',                   to: 'member#profile',                   as: 'profile'
  get 'search',                     to: 'publics#search',                   as: 'search'
  get 'portfolio/:id',              to: 'publics#portfolio',                as: 'portfolio'
  get "like/:id",                   to: "publics#upvote",                   as: 'like'
  get "document_download/:id",      to: "publics#document_download",        as: 'document_download'
  get "landing_page/:id",           to: "publics#landing_page",             as: 'landing_page'
  
  get "catalog_category_child",     to: "catalogs#catalog_category_child",  as: 'catalog_category_child'

  # Success review order
  get "review/:id",                 to: "orders#review",                    as: 'review'

  resources :catalogs do
    member do
      get 'comments'
      get 'support'
      get 'ticket'
      put "like",     to: "catalogs#upvote"
      match :upvote, path: 'like', via: [:get, :post, :put]
    end
  end

  resource :orders do
    collection do
      get :paid
      get :revoked
      post :ipn
    end
  end

  resources :order_items, only: [:create, :update, :destroy]
  resources :comments
  resources :tickets
  resources :subscribes

  # namespace :api do
  #   namespace :v1 do 
  #     resources :catalogs, only: [:index, :show] do 
  #       member do
  #         get 'comments'
  #         get 'support'
  #         get 'ticket'
  #         put "like",     to: "catalogs#upvote"
  #         match :upvote, path: 'like', via: [:get, :post, :put]
  #       end
  #     end
  #   end
  # end


end

app/models/member.rb
class Member < User
	extend FriendlyId
	friendly_id :username, use: [:slugged, :finders]
	default_scope { where(type: 'Member') }
end

app/models/order.rb
class Order < ActiveRecord::Base
  before_create :prepare_code
  extend FriendlyId
  friendly_id :code, use: [:slugged, :finders]

  belongs_to :user, foreign_key: 'user_id'
  has_many :order_items, foreign_key: 'order_id', dependent: :destroy

  accepts_nested_attributes_for :order_items, reject_if: :all_blank, allow_destroy: true

  scope :latest, ->{order(created_at: :desc)}
  scope :verified, ->{where(order_status_id: 2)}

  scope :bonds, -> {
    eager_load({
      user: [{profile: :address}]
    })
  }

  before_create :set_order_status
  before_save :update_subtotal

  def total
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.price) : 0 }.sum
  end

  def status?
    return '<span class="label label-warning">In Progress</span>'.html_safe if self.order_status_id == 1
    return '<span class="label label-success">Paid</span>'.html_safe if self.order_status_id == 2
    return '<span class="label label-important">Cancelled</span>'.html_safe if self.order_status_id == 3
  end

  def in_progress?
    self.order_status_id == 1
  end

  def paid?
    self.order_status_id == 2
  end

  def set_payment_token(token)
    self.payment_token = token
  end

  def self.pay(token, user, ordered, payerID)
    begin
      order = self.find_by_code(ordered.code)
      order.payment_token = token
      order.payerID = payerID
      order.purchased_at = Time.now
      order.order_status_id = 2
      if order
        order.order_items.map.each do |item|
          item.order_item_status = true
          item.save
        end
      end
      order.save
      @paypal = PaypalInterface.new(order)
      @paypal.do_express_checkout
      @paypal.get_express_checkout
      return order
    rescue
      false
    end
  end

  def set_transaction(transaction, payer_name, payer_email, payer_address)
    begin
      ordered = self
      ordered.transaction_id = transaction
      ordered.payer_name = payer_name
      ordered.payer_email = payer_email
      ordered.payer_address = payer_address
      ordered.save
      return ordered
    rescue
      false
    end
  end

  private
    include OrderSearch
    
    def set_order_status
      self.order_status_id = 1
      self.user_id = User.current.id
    end

    def update_subtotal
      self[:total] = total
    end

    def prepare_code
      self.code = SecureRandom.hex(6) if self.code.blank?
    end
end

app/controllers/backend/members_controller.rb
class Backend::MembersController < Backend::UsersController
	defaults resource_class: Member, collection_name: 'members', instance_name: 'member'
	include Backend::ActionMultiple

	def index
		@collection = collection.latest.page(page).per(per_page)
	end

	def change_position
		resource.change_verified_status!
		if resource.staff?
			UserMailer.send_user_to_staff(resource).deliver
			redirect_to :back, notice: "#{resource.username} has change to staff successfully"
		else
			redirect_to :back, notice: "#{resource.username} has change to member successfully"
		end
	end

	def change_featured
		resource.change_featured_status!
		if resource.featured?
			UserMailer.send_user_to_featured(resource).deliver
			redirect_to :back, notice: "#{resource.username} has featured successfully"
		else
			redirect_to :back, notice: "#{resource.username} has unfeatured successfully"
		end
	end

	private
    def collection
      @members ||= end_of_association_chain.search_by(params)
    end
end

app/controllers/backend/orders_controller.rb
class Backend::OrdersController < Backend::BackendApplicationController
	defaults resource_class: Order, collection_name: 'orders', instance_name: 'order'
	include Backend::ActionMultiple
	
	def index
		@collection = collection.latest.page(page).per(per_page)
	end

	def change_order_status
		@order = Order.find(params[:id])
		@order.update(order_status_id: params[:order][:order_status_id])
		if @order.save
			redirect_to :back, alert: 'Order status has changed'
		else
			redirect_to :back, error: 'Order status not changed'
		end
	end

	protected
		def collection
			@collection ||= end_of_association_chain.filter_search(params)
		end
end

app/controllers/member/catalogs_controller.rb
class Member::CatalogsController < Member::MemberApplicationController
	load_and_authorize_resource

	defaults resource_class: Catalog, collection_name: 'catalogs', instance_name: 'catalog'
	include Backend::ActionMultiple

	add_breadcrumb "Home", :root_path
	add_breadcrumb "Dashboard", :member_home_path
	add_breadcrumb "My Items", :member_catalogs_path

	def index
		@catalogs = collection.last_updated.where(user_id: current_user.id)
		@collection = @catalogs.page(page).per(per_page)
	end

	def new
		add_breadcrumb "New", new_member_catalog_path
	end

	def edit
		add_breadcrumb "Edit", edit_member_catalog_path(resource)
	end

	def create
		build_resource
		resource.catalog_category_id = params[:catalog_category_id]
    resource.user_id = current_user.id
    resource.save
    create! do |format|
      if resource.errors.empty?
      	UserMailer.send_catalog(resource).deliver
      	UserMailer.send_request_catalog(resource).deliver
        format.html { redirect_to member_catalogs_path}
      else 
        flash[:errors] = resource.errors.full_messages
        format.html { redirect_to :back}
      end
    end
	end

	def update
		resource.catalog_category_id = params[:catalog_category_id]
		resource.save
    update! do |format|
      if resource.errors.empty?
        format.html { redirect_to member_catalogs_path}
      else 
        flash[:errors] = resource.errors.full_messages
        format.html { redirect_to :back}
      end
    end
	end

	def document_download
	  @catalog = Catalog.find_by(code: params[:code])
    url = @catalog.file_catalog.url
    file_path = url.split("?").first
    if !file_path.nil?
			send_file "#{Rails.root}/public#{file_path}", :x_sendfile => true 
		else 
      redirect_to :back
		end
	end

	protected
		def collection
			@collection ||= end_of_association_chain.filter_search(params)
		end
end

app/controllers/member/favorites_controller.rb
class Member::FavoritesController < Member::MemberApplicationController
	defaults resource_class: Favorite, collection_name: 'favorites', instance_name: 'favorite'
	include Backend::ActionMultiple

	add_breadcrumb "Home", :root_path
	add_breadcrumb "Dashboard", :member_home_path
	add_breadcrumb "My Favorites", :member_favorites_path

	def index
		@favorites = collection.latest.where(user_id: current_user.id)
		@collection = @favorites.page(page).per(per_page)
	end

	def create
		filter = Favorite.where(catalog_id: params[:catalog_id], user_id: current_user.id)
    if filter.present?
      redirect_to catalog_path(params[:catalog_id]), alert: "Cannot save to favorites, Because you already save this item before"
    else
			build_resource
			resource.catalog_id = params[:catalog_id]
	    resource.user_id = current_user.id

	    resource.save
	    create! do |format|
	      if resource.errors.empty?
	        format.html { redirect_to member_favorites_path}
	      else 
	        flash[:errors] = resource.errors.full_messages
	        format.html { redirect_to :back}
	      end
	    end
	  end
	end

	protected
		def collection
			@collection ||= end_of_association_chain
		end
end

app/controllers/member/member_application_controller.rb
class Member::MemberApplicationController < ResourcesController
	layout 'member'
	before_filter :authenticate_user!
	protect_from_forgery with: :exception
	before_filter :prepare_data_user
	
	private
		def prepare_data_user
			@profile = current_user.try(:profile)
			@address = @profile.try(:address)
		end
end

app/controllers/member/members_controller.rb
class Member::MembersController < Member::MemberApplicationController
	load_and_authorize_resource
	defaults resource_class: Member, collection_name: 'members', instance_name: 'member'
	include Member::UserFilter

	add_breadcrumb "Home", :root_path
	add_breadcrumb "Dashboard", :member_home_path
	add_breadcrumb "Profile", :profile_path

	def edit
		add_breadcrumb "Settings", edit_member_member_path(current_user)
	end

	def update
		update! do |format|
      if resource.errors.empty?
        format.html { redirect_to :back}
      else 
        flash[:errors] = resource.errors.full_messages
        format.html { redirect_to :back}
      end
    end
	end
end

app/controllers/member/messages_controller.rb
class Member::MessagesController < Member::MemberApplicationController
	defaults resource_class: Message, collection_name: 'messages', instance_name: 'message'

	add_breadcrumb "Home", :root_path
	add_breadcrumb "Dashboard", :member_home_path
	add_breadcrumb "Messages", :member_messages_path

	def index
		@messages = collection.latest.where(to: current_user.email)
		@collection = @messages.page(page).per(per_page)
	end

	def show
		add_breadcrumb "Show"
		if resource
			resource.update(status: true)
			resource.save
		end
	end

	def create
		build_resource
		resource.user_id = current_user.id
		resource.status = true
		resource.save
		create! do |format|
			if resource.errors.empty?
        format.html { redirect_to :back }
      else 
        flash[:errors] = resource.errors.full_messages
        format.html { redirect_to :back }
      end
		end
	end

	protected
		def collection
			@collection ||= end_of_association_chain
		end
end

app/controllers/member/orders_controller.rb
class Member::OrdersController < Member::MemberApplicationController
	load_and_authorize_resource
	defaults resource_class: Order, collection_name: 'orders', instance_name: 'order'

	add_breadcrumb "Home", :root_path
	add_breadcrumb "Dashboard", :member_home_path
	add_breadcrumb "Invoice Orders", :member_orders_path

	def index
		@orders = collection.latest.where(user_id: current_user.id)
		@collection = @orders.page(page).per(per_page)
	end

	def show
		add_breadcrumb "Show"

		@order = collection.find(params[:id])
	end

	def destroy
		@resource = collection.find(params[:id])
		if @resource.destroy
			if session[:order_id] == @resource.id
				session[:order_id] = nil
			end
			redirect_to member_orders_path, alert: "You already cancel invoice order #{@resource.code}"
		else
			redirect_to member_orders_path, error: "Failed, you can't cancel"
		end
	end

	protected
		def collection
			@collection ||= end_of_association_chain
		end
end

app/controllers/member/tickets_controller.rb
class Member::TicketsController < Member::MemberApplicationController
	load_and_authorize_resource
	defaults resource_class: Ticket, collection_name: 'tickets', instance_name: 'ticket'
	include Backend::ActionMultiple

	add_breadcrumb "Home", :root_path
	add_breadcrumb "Dashboard", :member_home_path
	add_breadcrumb "Tickets", :member_tickets_path

	def home
	end
	
	def index		
		@tickets = collection.latest.where(user_id: current_user.id).filter_search(params)
		@collection = @tickets.page(page).per(per_page)
	end

	def new
		add_breadcrumb "New"
		build_resource
	end

	def show
		add_breadcrumb "Show"
		@messages = resource.messages.oldest
		@message = Message.new
	end

	def create
		build_resource
    resource.user_id = current_user.id
    resource.save
    create! do |format|
      if resource.errors.empty?
      	UserMailer.send_ticket(resource).deliver
        format.html { redirect_to member_tickets_path}
      else 
        flash[:errors] = resource.errors.full_messages
        format.html { redirect_to :back}
      end
    end
	end

	protected
		def collection
			@collection ||= end_of_association_chain
		end
end

app/controllers/member_controller.rb
class MemberController < Member::MemberApplicationController
	layout 'member'
	add_breadcrumb "Home", :root_path

	def home
		add_breadcrumb "Dashboard", member_home_path
		add_breadcrumb "#{current_user.username.titleize}"

		@catalogs = current_user.catalogs.last_updated.limit(12)
	end

	def profile
		add_breadcrumb "Dashboard", member_home_path
		add_breadcrumb "Profile", profile_path
		add_breadcrumb "#{current_user.username.titleize}"
	end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	add_breadcrumb "Home", :root_path

  def paid
    if order = Order.pay(params[:token], current_user, current_order, params[:PayerID])
    	if current_order
    		UserMailer.send_invoice(current_order).deliver
				session[:order_id] = nil
			end
      redirect_to review_path(params[:token]), notice: 'Thanks, your order is successfully paid, please check your email to see evidence of the invoice has been paid, or you can see the details below!'
    else
      redirect_to orders_path, alert: 'Something went wrong. Please try again.'
    end
  end

  def revoked
  	redirect_to orders_path, alert: 'Your order has been cancelled.'
  end

  def ipn
    if payment = Payment.find_by_transaction_id(params[:txn_id])
      payment.receive_ipn(params)
    else
      Payment.create_by_ipn(params)
    end
  end

  def review
    add_breadcrumb "Success complete order"

    @order = Order.find_by(payment_token: params[:id])
    unless @order && current_user
      redirect_to root_path, notice: 'You do not have permission to access this page'
    end
  end
	
	def show
		add_breadcrumb "My Order Items", orders_path

		@order = current_order
		@order_items = @order.order_items

    if @order
	    @paypal = PaypalInterface.new(@order)
		  @paypal.express_checkout
		  if @paypal.express_checkout_response.success?
		    @paypal_url = @paypal.api.express_checkout_url(@paypal.express_checkout_response)
		  else
		    redirect_to root_path, notice: "Something went wrong. You must order item first before view this page, Please try again."
		  end
		end
  end
end

app/views/member/orders/index.html.erb
<div class="col-md-8 main">
  <h2>
    <div class="row">
      <div class="col-md-7">
        My Invoice Orders
      </div>
    </div>
  </h2>
  <div class="catalog-item-show">
    <div class="table-responsive">
      <% if @collection.present? %>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Action</th>
              <th width="30%">Invoice Code</th>
              <th>Created At</th>
              <th class="text-center">Status</th>
            </tr>
          </thead>
          <tbody>
            <% @collection.each do |resource| %>
              <tr>
                <td>
                  <% if resource.paid? %>
                    <%= link_to resource_path(resource), class: "label label-info" do %>
                      Show
                    <% end %>
                  <% elsif resource.in_progress? %>
                    <%= link_to resource_path(resource), method: 'delete', data: {confirm: 'you want cancel this order?'} do %>
                      <div class="btn btn-danger btn-xs">
                        Cancel
                      </div>
                    <% end %>
                  <% end %>
                </td>
                <td><b><%= resource.code %></b></td>
                <td><%= resource.try(:created_at).strftime("%H:%M %B, %d, %Y") if resource.try(:created_at).present? %></td>
                <th class="text-center">
                  <%= resource.status? %>
                </th>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @collection %>
      <% else %>
        <p class="p-error">Data is still empty!</p>
      <% end %>
    </div>
  </div>
</div>

app/views/member/orders/show.html.erb
<div class="col-md-12">
  <div class="row">
    <div class="col-md-12">
      <% if @order.paid? %>
        <h3 class="text-center">
          <strong>Invoice Order <%= @order.code %> Completed <%= @order.status? %></strong>
        </h3>
        <div class="align-center">
          <b>Your Transaction id : </b>
          <%= @order.try(:transaction_id) %><br>
          <b>Price : </b>
          <%= number_to_currency_br(@order.total) %><br>
          <b>PayerID : </b>
          <%= @order.try(:payerID) %><br>
          <b>Payer Name : </b>
          <%= @order.try(:payer_name) %><br>
          <b>Payer Email : </b> 
          <a href="mailto<%= @order.try(:payer_email) %>"><%= @order.try(:payer_email) %></a><br>
          <b>Payer Address : </b>
          <%= @order.try(:payer_address) %><br>
          <b>Payment Date : </b> 
          <%= @order.try(:purchased_at).strftime("%H:%M %B, %d, %Y") if @order.purchased_at %><br>
          <b>Payment Status : </b>
          Completed
        </div>
      <% end %>
      <div class="panel panel-default margin-top20">
        <div class="panel-body wrapper-order-list">
          <div class="table-responsive table-order-list">
            <table class="table table-condensed">
              <thead>
                <tr>
                  <% unless @order.paid? %>
                    <td><strong>Action</strong></td>
                  <% end %>
                  <td width="45%"><strong>Item Name</strong></td>
                  <td class="text-center"><strong>Quantity</strong></td>
                  <% if @order.paid? %>
                    <td class="text-center"><strong>File</strong></td>
                  <% end %>
                  <td class="text-center"><strong>Ordered At</strong></td>
                  <td class="text-right"><strong>Item Price</strong></td>
                </tr>
              </thead>
              <tbody>
                <% @order.order_items.each do |order_item| %>
                  <tr>
                    <% unless @order.paid? %>
                      <td>
                        <p>
                          <%= link_to "<i class='fa fa-close'></i> Delete".html_safe, order_item, { data: { confirm: "Are you sure you wish to delete the item '#{order_item.catalog.title}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger btn-xs margin-right5" } %>
                        </p>
                      </td>
                    <% end %>
                    <td>
                      <h5 class="image-order-list">
                        <%= image_tag order_item.try(:catalog).try(:thumbnail).url(:small) %>
                        <%= link_to "#{order_item.catalog.title}", catalog_path(order_item.catalog.slug) %>
                      </h5>
                    </td>
                    <td class="text-center">
                      <p class="bold">
                        <%= order_item.try(:quantity) %>
                      </p>
                    </td>
                    <% if @order.paid? %>
                      <td class="text-center">
                        <%= link_to document_download_url(order_item.catalog.code) do %>
                          <p>Download</p>
                        <% end %>
                      </td>
                    <% end %>
                    <td class="text-center">
                      <p>
                        <%= order_item.try(:created_at).strftime("%H:%M %B, %d, %Y") %>
                      </p>
                    </td>
                    <td class="text-right">
                      <p class="bold">
                        <%= number_to_currency_br(order_item.total_price) %>
                      </p>
                    </td>
                  </tr>
                <% end %>
                <tr>
                  <% unless @order.paid? %>
                    <td class="highrow"></td>
                  <% end %>
                  <td class="highrow"></td>
                  <td class="highrow"></td>
                  <% if @order.paid? %>
                    <td class="highrow"></td>
                  <% end %>
                  <td class="highrow text-center"><h4>TOTAL</h4></td>
                  <td class="highrow text-right"><h4><%= number_to_currency_br(@order.total) %></h4></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>